"""Pydantic models for Artemis requests and responses.

This module defines all request/response schemas using Pydantic for validation.
The models support two API patterns:
1. /search endpoint - Simple search with optional summarization
2. /v1/responses endpoint - Perplexity-compatible API with deep research support

All models include validation constraints (min/max lengths, value ranges) to
ensure API contracts are enforced at runtime.
"""

from typing import Literal

from pydantic import BaseModel, Field, computed_field


class SearchResult(BaseModel):
    """Individual search result from SearXNG.

    Represents a single web search result with title, URL, snippet, and
    optional publication date.

    Attributes:
        title: Result title (often clickable heading)
        url: Full URL to the result
        snippet: Text excerpt from the result
        date: Publication date if available (ISO format preferred)
    """

    title: str
    url: str
    snippet: str
    date: str | None = None


class TokenUsage(BaseModel):
    """Token consumption tracking for LLM API calls.

    Tracks input, output, and total tokens used across all LLM requests
    in a single operation. Default values are 0 for easy aggregation.

    Includes both OpenAI Responses API field names (input_tokens/output_tokens)
    and Chat Completions API field names (prompt_tokens/completion_tokens) so
    LiteLLM billing can read usage from either format.

    Also tracks search-specific usage for LiteLLM web search billing:
    - search_requests: Number of upstream search API calls made
    - citation_tokens: Estimated tokens from search content injected into LLM prompts

    Attributes:
        input_tokens: Tokens sent in the prompt/request
        output_tokens: Tokens received in the completion/response
        total_tokens: Sum of input and output tokens
        search_requests: Number of search API calls made
        citation_tokens: Estimated tokens from search-derived content
        prompt_tokens: Alias of input_tokens (Chat Completions API format)
        completion_tokens: Alias of output_tokens (Chat Completions API format)
    """

    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0
    search_requests: int = 0
    citation_tokens: int = 0

    @computed_field  # type: ignore[prop-decorator]
    @property
    def prompt_tokens(self) -> int:
        """Chat Completions API alias for input_tokens."""
        return self.input_tokens

    @computed_field  # type: ignore[prop-decorator]
    @property
    def completion_tokens(self) -> int:
        """Chat Completions API alias for output_tokens."""
        return self.output_tokens


class SearchRequest(BaseModel):
    """Request model for the /search endpoint.

    Validates and constrains search parameters received from clients.

    Attributes:
        query: Search query string (1-500 chars)
        max_results: Maximum results to return (1-50, default: 10)
        search_domain_filter: Optional list of domains to restrict search
    """

    query: str = Field(min_length=1, max_length=500)
    max_results: int = Field(default=10, ge=1, le=50)
    search_domain_filter: list[str] | None = Field(default=None, max_length=25)


class SearchResponse(BaseModel):
    """Response model for the /search endpoint.

    Contains search results, optional LLM summary, token usage, and warnings.

    Attributes:
        id: Unique identifier for this response
        results: List of search results from SearXNG
        summary: LLM-generated summary if enabled (None otherwise)
        usage: Token usage for summarization if applicable
        warnings: List of warning messages (e.g., summarization failures)
    """

    id: str
    results: list[SearchResult]
    summary: str | None = None
    usage: TokenUsage | None = None
    warnings: list[str] = Field(default_factory=list)


class ResponsesRequest(BaseModel):
    """Request model for Perplexity-compatible /v1/responses endpoint.

    Supports three modes:
    - "fast-search": Single search with optional summarization
    - "shallow-research": Single-pass research with shallower preset defaults
    - "deep-research": Multi-stage research with essay synthesis

    Attributes:
        input: Research query or topic (1-4000 chars)
        preset: Operation mode (default: fast-search)
        outline: Optional custom outline (list of section/description). Overrides config.
        streaming: Enable server-sent events streaming (default: false)
    """

    input: str = Field(min_length=1, max_length=4000)
    preset: Literal["fast-search", "shallow-research", "deep-research"] = "fast-search"
    outline: list[dict[str, str]] | None = None
    max_steps: int | None = Field(default=None, ge=1, le=10)
    streaming: bool = False


class OutputText(BaseModel):
    """Text output block for Perplexity-style API responses.

    Represents a piece of text content generated by the LLM.
    """

    type: Literal["output_text"] = "output_text"
    text: str


class AssistantMessage(BaseModel):
    """Assistant message block for Perplexity-style API responses.

    Represents a complete assistant response with generated content.

    Attributes:
        id: Unique message identifier
        status: Always "completed" for successful responses
        role: Always "assistant"
        content: List of output text blocks
    """

    type: Literal["message"] = "message"
    id: str
    status: Literal["completed"] = "completed"
    role: Literal["assistant"] = "assistant"
    content: list[OutputText]


class SearchResultItem(BaseModel):
    """Search result item for Perplexity-style API responses.

    Similar to SearchResult but formatted for the Perplexity-compatible
    output structure with source metadata.

    Attributes:
        id: Numeric index of the result
        url: Full URL to the result
        title: Result title
        snippet: Text excerpt
        date: Publication date if available
        source: Content source (always "web" for web search)
    """

    id: int
    url: str
    title: str
    snippet: str
    date: str | None = None
    source: Literal["web"] = "web"


class SearchResultsBlock(BaseModel):
    """Search results block for Perplexity-style API responses.

    Contains a list of search result items in the format expected
    by Perplexity-compatible clients.
    """

    type: Literal["search_results"] = "search_results"
    results: list[SearchResultItem]


class ResponsesAPIResponse(BaseModel):
    """Response model for Perplexity-compatible /v1/responses endpoint.

    Matches the OpenAI Responses API format.

    Attributes:
        id: Unique response identifier
        created: Unix timestamp of creation
        model: Model identifier used
        status: Always "completed" for successful responses
        output: List of message and/or search results blocks
        usage: Aggregated token usage across all operations
        warnings: Operational warnings to communicate to client
    """

    id: str
    object: Literal["response"] = "response"
    created: int
    model: str
    status: Literal["completed"] = "completed"
    output: list[AssistantMessage | SearchResultsBlock]
    usage: TokenUsage = Field(default_factory=TokenUsage)
    warnings: list[str] = Field(default_factory=list)


class DeepResearchRun(BaseModel):
    """Complete deep research operation result.

    Contains the synthesized essay, all gathered results, sub-queries used,
    and aggregated token usage across all research stages.

    Attributes:
        essay: Final synthesized research essay
        results: All search results gathered across stages
        sub_queries: All sub-queries generated during research
        stages_completed: Number of research stages executed
        usage: Aggregated token usage across all stages
    """

    essay: str
    results: list[SearchResult]
    sub_queries: list[str]
    stages_completed: int
    usage: TokenUsage = Field(default_factory=TokenUsage)
